/* Generado por tools/make-pixel-icons.py — no editar a mano. */
window.PIXEL_ICONS = {
  invader: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAN0lEQVR42mNgGH7A617Df1LEiTKEZM24MNGa0Q1ClyPZZqJcgs1mbBqJMoAceazhgE9sFFARAAA7LHoDJz6BMAAAAABJRU5ErkJggg==",
  heart: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAUElEQVR42mNgGDRgn5DNfxgmWR4k+LuwFY7RFeGVR5eEKYApgrGxqcFpALIh+OTxGoAPY4QDqYYQFZBEayTWEIKaCcUKyYmKbM3oKY9h+AMA4VYMYfCB/pAAAAAASUVORK5CYII=",
  floppy: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAPUlEQVR42mNgoAaQs+r6Tw7GacDpqw+xYooMcA/NHEoGUByIZBnw49cfkjBWA0D+JAbjNGCIu4CiWBhQAABtcc0Wbkzk4QAAAABJRU5ErkJggg==",
  ghost: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAO0lEQVR42mNgGJRgRej3/9gw2RqJMohYzTgNgUnAALoGdHG8BshJe2M1AFmcIudjGDJqABUNIJc/sAAAl7CsFj66o9UAAAAASUVORK5CYII=",
  cassette: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAATklEQVR42mNgGBRAUEL9PzkYxYCfxWIkYawG/H3WRRTGawDMeeia0MXxGoDLZqIMoMgLFAciCNfoCuHFBA2g2AUgPjIbnY/TAIpS4tAGAMSPVFIaJoJgAAAAAElFTkSuQmCC",
};
